spring:
  datasource:
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    url: jdbc:postgresql://${DB_ADDR:localhost}:${DB_PORT:5432}/${DB_DATABASE:my_forum}
  jpa:
    show-sql: true
    hibernate:
      default_schema: public
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
  flyway:
    enabled: true
    user: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    url: jdbc:postgresql://${DB_ADDR:localhost}:${DB_PORT:5432}/${DB_DATABASE:my_forum}
    baseline-on-migrate: true
